const followedChannels = [
  {
    user: "casimito",
    game: "Just Chatting",
    viewers: 28214,
    tags: ["Português"],
    avatar: "/users/casimito.png",
    color: "#C0F500",
  },
  {
    user: "alanzoka",
    game: "Scorn",
    viewers: 10920,
    tags: ["Português"],
    avatar: "/users/alanzoka.png",
  },
  {
    user: "YoDa",
    game: "League of Legends",
    viewers: 7467,
    tags: ["Português"],
    avatar: "/users/YoDa.png",
    color: "#4156BE",
  },
  {
    user: "Baiano",
    game: "League of Legends",
    viewers: 7430,
    tags: ["Português"],
    avatar: "/users/Baiano.png",
    color: "#FFA435",
  },
  {
    user: "frttt",
    game: "VALORANT",
    viewers: 4300,
    tags: ["Português"],
    avatar: "/users/frttt.png",
  },
  {
    user: "Coreano",
    game: "Overwatch 2",
    viewers: 3405,
    tags: ["Português"],
    avatar: "/users/Coreano.png",
    color: "#000000",
  },
  {
    user: "Felps",
    game: "Cookie Clicker",
    viewers: 2231,
    tags: ["Português"],
    avatar: "/users/Felps.png",
    color: "#FF3D6C",
  },
  {
    user: "TFToddy",
    game: "Teamfight Tactics",
    viewers: 1879,
    tags: ["Português"],
    avatar: "/users/TFToddy.png",
    color: "#1E1B5E",
  },
  {
    user: "Prizzaa",
    game: "Just Chatting",
    viewers: 723,
    tags: ["Português"],
    avatar: "/users/Prizzaa.png",
    color: "#FAB3FF",
  },
  {
    user: "nuuhfps",
    game: "VALORANT",
    viewers: 643,
    tags: ["Português"],
    avatar: "/users/nuuhfps.png",
    color: "#EFF133",
  },
  {
    user: "laribasgal",
    game: "Overwatch 2",
    viewers: 540,
    tags: ["Português"],
    avatar: "/users/laribasgal.png",
    color: "#F5F064",
  },
  {
    user: "PatoPapao",
    game: "League of Legends",
    viewers: 532,
    tags: ["Português"],
    avatar: "/users/PatoPapao.png",
    color: "#00C7AC",
  },
];

const recommendedChannels = [
  {
    user: "Recommended 1",
    game: "Minecraft",
    viewers: 1100,
    tags: ["English"],
  },
  {
    user: "Recommended 2",
    game: "Terraria",
    viewers: 70,
    tags: ["English"],
  },
  {
    user: "Recommended 3",
    game: "VALORANT",
    viewers: 4800,
    tags: ["English"],
  },
  {
    user: "Recommended 4",
    game: "Overwatch 2",
    viewers: 19,
    tags: ["English"],
  },
  {
    user: "Recommended 5",
    game: "League of Legends",
    viewers: 436,
    tags: ["English"],
  },
  {
    user: "Recommended 6",
    game: "Teamfight Tactics",
    viewers: 248,
    tags: ["English"],
  },
];

const categories = [
  {
    name: "VALORANT",
    image: "/categories/valorant.jpg",
    viewers: 108200,
    tags: ["Shooter", "FPS"],
  },
  {
    name: "Sports",
    image: "/categories/sports.jpg",
    viewers: 146829,
    tags: ["IRL"],
  },
  {
    name: "Just Chatting",
    image: "/categories/just-chatting.jpg",
    viewers: 376239,
    tags: ["IRL"],
  },
  {
    name: "Teamfight Tactics",
    image: "/categories/teamfight-tactics.jpg",
    viewers: 16440,
    tags: ["Strategy"],
  },
  {
    name: "League of Legends",
    image: "/categories/league-of-legends.jpg",
    viewers: 93854,
    tags: ["MOBA", "Action"],
  },
  {
    name: "Overwatch 2",
    image: "/categories/overwatch-2.jpg",
    viewers: 42320,
    tags: ["FPS", "Shooter"],
  },
  {
    name: "Genshin Impact",
    image: "/categories/genshin-impact.jpg",
    viewers: 26602,
    tags: ["Action", "RPG"],
  },
  {
    name: "Pokémon Scarlet/Violet",
    image: "/categories/pokemon-scarlet.jpg",
    viewers: 61320,
    tags: ["RPG"],
  },
  {
    name: "Minecraft",
    image: "/categories/minecraft.jpg",
    viewers: 136620,
    tags: ["MMO"],
  },
  {
    name: "Red Dead Redemption 2",
    image: "/categories/red-read-redemption.jpg",
    viewers: 2630,
    tags: ["Action"],
  },
  {
    name: "Art",
    image: "/categories/art.jpg",
    viewers: 12720,
    tags: ["Creative", "IRL"],
  },
  {
    name: "God of War Ragnarök",
    image: "/categories/gow-ragnarock.jpg",
    viewers: 16720,
    tags: ["Action"],
  },
];

export { followedChannels, recommendedChannels, categories };
