const followedChannels = [
  {
    user: "casimito",
    game: "Just Chatting",
    viewers: 28214,
    tags: ["Português"],
    avatar: "/users/casimito.png",
    color: "#C0F500",
  },
  {
    user: "alanzoka",
    game: "Scorn",
    viewers: 10920,
    tags: ["Português"],
    avatar: "/users/alanzoka.png",
  },
  {
    user: "YoDa",
    game: "League of Legends",
    viewers: 7467,
    tags: ["Português"],
    avatar: "/users/YoDa.png",
    color: "#4156BE",
  },
  {
    user: "Baiano",
    game: "League of Legends",
    viewers: 7430,
    tags: ["Português"],
    avatar: "/users/Baiano.png",
    color: "#FFA435",
  },
  {
    user: "frttt",
    game: "VALORANT",
    viewers: 4300,
    tags: ["Português"],
    avatar: "/users/frttt.png",
  },
  {
    user: "Coreano",
    game: "Overwatch 2",
    viewers: 3405,
    tags: ["Português"],
    avatar: "/users/Coreano.png",
    color: "//#endregion000000",
  },
  {
    user: "Felps",
    game: "Cookie Clicker",
    viewers: 2231,
    tags: ["Português"],
    avatar: "/users/Felps.png",
  },
  {
    user: "TFToddy",
    game: "Teamfight Tactics",
    viewers: 1879,
    tags: ["Português"],
    avatar: "/users/TFToddy.png",
  },
  {
    user: "nuuhfps",
    game: "VALORANT",
    viewers: 643,
    tags: ["Português"],
    avatar: "/users/nuuhfps.png",
  },
  {
    user: "laribasgal",
    game: "Overwatch 2",
    viewers: 540,
    tags: ["Português"],
    avatar: "/users/laribasgal.png",
  },
  {
    user: "PatoPapao",
    game: "League of Legends",
    viewers: 532,
    tags: ["Português"],
    avatar: "/users/PatoPapao.png",
  },
  {
    user: "MrFalll",
    game: "Raid: Shadow Legends",
    viewers: 174,
    tags: ["Português"],
    avatar: "/users/MrFalll.png",
  },
];

const recommendedChannels = [
  {
    user: "Recommended 1",
    game: "Minecraft",
    viewers: 1100,
    tags: ["English"],
  },
  {
    user: "Recommended 2",
    game: "Terraria",
    viewers: 70,
    tags: ["English"],
  },
  {
    user: "Recommended 3",
    game: "VALORANT",
    viewers: 4800,
    tags: ["English"],
  },
  {
    user: "Recommended 4",
    game: "Overwatch 2",
    viewers: 19,
    tags: ["English"],
  },
  {
    user: "Recommended 5",
    game: "League of Legends",
    viewers: 436,
    tags: ["English"],
  },
  {
    user: "Recommended 6",
    game: "Teamfight Tactics",
    viewers: 248,
    tags: ["English"],
  },
];

export { followedChannels, recommendedChannels };
